apiVersion: v1
kind: Secret
metadata:
  name: collab-secrets
  namespace: collab
type: Opaque
stringData:
  JWT_SECRET: "change_me_in_production_use_a_long_random_string"
  POSTGRES_PASSWORD: "collabpass123"