apiVersion: apps/v1
kind: Deployment
metadata:
  name: persistence
  namespace: collab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: persistence
  template:
    metadata:
      labels:
        app: persistence
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: persistence
          image: ghcr.io/babacarane/collab-editor/persistence:latest
          envFrom:
            - configMapRef:
                name: collab-config
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: collab-secrets
                  key: JWT_SECRET
          readinessProbe:
            exec:
              command: ["node", "-e", "process.exit(0)"]
            initialDelaySeconds: 10
            periodSeconds: 10