apiVersion: v1
kind: Service
metadata:
  name: collab
  namespace: collab
  annotations:
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "collab-sticky"
    nginx.ingress.kubernetes.io/session-cookie-expires: "86400"
spec:
  selector:
    app: collab
  ports:
    - port: 4000
      targetPort: 4000